"""empty message

Revision ID: 01ada6b49c6c
Revises: 33ecd300c3da
Create Date: 2022-10-26 15:15:47.849704

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "01ada6b49c6c"
down_revision = "33ecd300c3da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("product", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "product", "category", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_column("product", "category_id")
    op.drop_table("category")
    # ### end Alembic commands ###
