"""empty message

Revision ID: 33ecd300c3da
Revises: 5076e02659f9
Create Date: 2022-10-04 10:55:38.106349

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "33ecd300c3da"
down_revision = "5076e02659f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column("picture", sqlalchemy_utils.types.url.URLType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "picture")
    # ### end Alembic commands ###
