"""empty message

Revision ID: 5076e02659f9
Revises: 950c225a3f6d
Create Date: 2022-10-01 12:58:48.883179

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5076e02659f9"
down_revision = "950c225a3f6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "price",
        existing_type=mysql.DECIMAL(precision=10, scale=0),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=mysql.DECIMAL(precision=10, scale=0),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
