"""empty message

Revision ID: 950c225a3f6d
Revises: 9c8320bd96c2
Create Date: 2022-10-01 12:13:12.951570

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "950c225a3f6d"
down_revision = "9c8320bd96c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("price", sa.Numeric(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "price")
    # ### end Alembic commands ###
