"""empty message

Revision ID: a8445019b447
Revises: 17aa23c8eaa1
Create Date: 2023-03-11 18:04:09.864802

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a8445019b447"
down_revision = "17aa23c8eaa1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product", "price")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product",
        sa.Column("price", mysql.DECIMAL(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###
